<?php

namespace CatalogueBundle\Repository;

/**
 * TableBlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableBlogRepository extends \Doctrine\ORM\EntityRepository
{
}
